### ISSUE TITLE
修改网页tracker

### ISSUE THREAD

**Issue by liuboss1992** [AlphaJia/alphajia.github.io#1]
```
鹏飞，你好！
	我注意到，你好像是仿照我的个人主页（http://home.ustc.edu.cn/~lcb592/）的格式，制作了自己的主页，并挂载到自己域名的网站上。这样的宣传确实非常有吸引力~
	不过，有一个小问题需要和你交流。我在我的个人主页中添加了属于我自己的tracker （rf.revolvermaps.com 相关脚本></script>），用于统计流量。可能你时间比较匆忙，并没有对这个tracker进行改动，因此在你的网页中，继续使用着我的tracker。
	因此，目前咱们二人的流量统计已经发生了混淆。。。我也正是通过在分析访客时，发现了流量有别的入口，才找到了你那里的“世外桃源”。
	
	你可否花一点时间，替换成自己的tracker？
	目前有很多平台都提供tracker脚本，我是从 https://clustrmaps.com/ 这个网站申请的。制作方法非常简单，两三分钟就能搞定~
	如果你感兴趣，我也可以分享给你我制作网页的工具软件，方便你以后更好的制作网页。
```

**Comment by AlphaJia** [comment]
> ```
> 鹏飞，你好！
> 	我注意到，你好像是仿照我的个人主页（http://home.ustc.edu.cn/~lcb592/）的格式，制作了自己的主页，并挂载到自己域名的网站上。这样的宣传确实非常有吸引力~
> 	不过，有一个小问题需要和你交流。我在我的个人主页中添加了属于我自己的tracker （rf.revolvermaps.com 相关脚本></script>），用于统计流量。可能你时间比较匆忙，并没有对这个tracker进行改动，因此在你的网页中，继续使用着我的tracker。
> 	因此，目前咱们二人的流量统计已经发生了混淆。。。我也正是通过在分析访客时，发现了流量有别的入口，才找到了你那里的“世外桃源”。
> 	
> 	你可否花一点时间，替换成自己的tracker？
> 	目前有很多平台都提供tracker脚本，我是从 https://clustrmaps.com/ 这个网站申请的。制作方法非常简单，两三分钟就能搞定~
> 	如果你感兴趣，我也可以分享给你我制作网页的工具软件，方便你以后更好的制作网页。
> ```

Hi, 传彬，真的很抱歉。之前看了你的个人网页，制作的很好，所以进行了借鉴。由于自己对网页制作几乎零基础，没想到在参考的时候给你带来不便。我已经删除了相关tracker，不知道直接删除是否还会有问题？若有问题，麻烦告知一下。

**Comment by liuboss1992** [comment]
Hi 鹏飞~感谢你的修改~问题已经解决。
我制作网页时使用的是mac上的blocs软件，很容易上手。你可以通过它维护自己的网页。
比如，你标签页上的图片，目前还是我科的校徽，你可以尝试替换一下 (*^_^*)

**Comment by AlphaJia** [comment]
好的，谢谢。我试一下
